import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

export type LanguageType = "RU" | "EN";
export const availableLanguages: LanguageType[] = ["RU", "EN"];

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Portfolio. Daniil Sychev",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={"en"} suppressHydrationWarning>
      <body
        className={`${inter.className} bg-white text-black dark:bg-[#090908] dark:text-white h-full selection:bg-gray-50 dark:selection:bg-gray-800`}
      >
        {children}
      </body>
    </html>
  );
}
