import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "./components/Navbar";
import { Progress } from "./components/Progress";
import { ThemeContextProvider } from "./context/ThemeContext";
import { LanguageContextProvider } from "./context/LangContext";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio. Daniil Sychev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} bg-white text-black dark:bg-[#090908] dark:text-white h-full selection:bg-gray-50 dark:selection:bg-gray-800`}
      >
        <Progress />
        <LanguageContextProvider>
          <ThemeContextProvider>
            <Navbar />
            <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
              {children}
            </main>
          </ThemeContextProvider>
        </LanguageContextProvider>
      </body>
    </html>
  );
}
